{% set version = "21.21.19914" %}

package:
  name: intel-compute-runtime
  version: {{ version }}

source:
  url: https://github.com/intel/compute-runtime/archive/{{ version }}.tar.gz
  sha256: a9573af507a5482cf27672a636f04b4329e36fabc72e1c0a0fe686832c4f95d7
  patches:
    - gh412.patch

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
  host:
    - intel-gmmlib
    - intel-graphics-compiler
  run:
    - {{ pin_compatible("intel-gmmlib", exact=True) }}
    - {{ pin_compatible("intel-graphics-compiler", exact=True) }}

test:
  commands:
    - test -f ${PREFIX}/lib/intel-opencl/libigdrcl${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/etc/OpenCL/vendors/intel.icd  # [unix]

about:
  home: https://github.com/intel/compute-runtime
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Intel(R) Graphics Compute Runtime for OpenCL(TM)

extra:
  recipe-maintainers:
    - isuruf
