{% set version = "20.09.15980" %}

package:
  name: intel-compute-runtime
  version: {{ version }}

source:
  url: https://github.com/intel/compute-runtime/archive/{{ version }}.tar.gz
  sha256: 26ac5e2f175e5aa53bed322d4f996b4218621e4cc4e3c00a6874224dc3b9c8f2
  patches:
    - add_rt.diff
    - install_icd.diff

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
  host:
    - intel-gmmlib
    - intel-graphics-compiler
  run:
    - {{ pin_compatible("intel-gmmlib", exact=True) }}
    - {{ pin_compatible("intel-graphics-compiler", exact=True) }}

test:
  commands:
    - test -f ${PREFIX}/lib/intel-opencl/libigdrcl${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/etc/OpenCL/vendors/intel.icd  # [unix]

about:
  home: https://github.com/intel/compute-runtime
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Intel(R) Graphics Compute Runtime for OpenCL(TM)

extra:
  recipe-maintainers:
    - isuruf
